# Generated by Django 2.0.4 on 2018-08-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180822_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_edit_books', 'Create, update or delete books'),)},
        ),
    ]
